# Generated by Django 3.0.7 on 2020-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amiispace_app', '0002_auto_20200622_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
