# Generated by Django 3.0.7 on 2020-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amiispace_app', '0006_auto_20200626_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycard',
            name='bought_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='selling_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
